### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by ateucher** [ropenscilabs/jsonvalidate#1]
Hi @richfitz  - do you have plans to push this to CRAN? @sckott and I are working on a package that supplies a few different methods for validating geojson ([geojsonlint](https://github.com/ropenscilabs/geojsonlint)), and currently have `jsonvalidate` as a dependency. We are hoping to push to CRAN relatively soon - we can remove the function that depends on `jsonvalidate` for now if you're not planning to submit to CRAN, but if you have plans to do that in the near future, we will hold off. Thanks!

**Comment by richfitz** [comment]
Sure thing!  I just need to get some more tests in here as what is in the package was literally 2-3 hours work at the unconf.  Let me take a look at what state it's in later in the week and see how it looks for CRAN submission.

**Comment by ateucher** [comment]
Awesome, thanks!

**Comment by sckott** [comment]
anything we can help with to get it to CRAN ?

**Comment by richfitz** [comment]
Mostly I just need to know that it works for some nontrivial use case now. Is it working OK for you?  I think that Jeroen has it working on the datapkg package.  I'll try and get this parcelled off soon, though I have to do an update of another package first at CRAN's request.

**Comment by sckott** [comment]
Yeah, works fine for me

**Comment by richfitz** [comment]
Submitted.

**Comment by richfitz** [comment]
And on CRAN! :tada:

**Comment by sckott** [comment]
thx

**Comment by ateucher** [comment]
Nice!
